# Generated by Django 4.0.6 on 2022-07-06 10:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Skills',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill', models.CharField(max_length=50, null=True)),
                ('resume', models.ForeignKey(blank=True, default=0, on_delete=django.db.models.deletion.CASCADE, to='resume.resume')),
            ],
        ),
    ]
