# Generated by Django 4.0.5 on 2022-06-30 19:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0002_alter_education_resume_alter_experience_resume_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='education',
            old_name='descreption',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='experience',
            old_name='descreption',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='publications',
            old_name='descreption',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='work',
            old_name='descreption',
            new_name='description',
        ),
    ]
