# Generated by Django 4.0.5 on 2022-06-30 19:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0003_rename_descreption_education_description_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='education',
            old_name='degrees',
            new_name='degree',
        ),
    ]
